# Generated by Django 4.2 on 2023-04-10 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texto', '0002_feat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feat',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feats', to='texto.music', verbose_name='Musica'),
        ),
    ]
