# Generated by Django 4.2 on 2023-04-23 02:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Cantor')),
            ],
            options={
                'verbose_name': 'Cantor',
                'verbose_name_plural': 'Cantores',
            },
        ),
        migrations.AddIndex(
            model_name='singer',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('name', config='portuguese'), name='singer_search_vector_idx'),
        ),
    ]
